### PR TITLE
[WIP] Integrate Show and Tell model

### PR DESCRIPTION
**Pull request by leesharma**
The goal of this PR is to integrate the Show and Tell model for caption generation. This involves setting up tensorflow, adding the model and checkpoint, and adding a `ShowAndTell` class to actually run the example.

Source: https://github.com/KranthiGV/Pretrained-Show-and-Tell-model

### CODE REVIEW

**Comment by leesharma** [comment]
I found another version of the trained model linked here: https://edouardfouche.com/Fun-with-Tensorflow-im2txt/.

If we get bad results with the current version, we can try that as a plan B. It looks like it is 3M iterations (vs. the 1M and 2M from GitHub).

**Review by bchertel — APPROVED** [review]
Changes look good

**Comment by leesharma** [comment]
Hey @bchertel, this wasn't done yet. I'll open a new PR with the new changes, but WIP="Work in Progress".

**Comment by bchertel** [comment]
My apologies, still getting used to the PR workflow.

**Pull request merged**
